import { createHmac, randomUUID, timingSafeEqual } from "node:crypto";
import type { Db } from "./db";
import { mutateUser } from "./db";
import { approvedInstallationAccount } from "./installations";
import type { ReviewBotConfig } from "./config";
import { changedTaskPaths, projectOpenSpec } from "./openspec";

export function githubSignatureValid(body: string, signature: string | null, secret: string) { if (!signature?.startsWith("sha256=")) return false; const expected = createHmac("sha256", secret).update(body).digest("hex"), actual = signature.slice(7); return actual.length === expected.length && timingSafeEqual(Buffer.from(actual), Buffer.from(expected)); }
export async function acceptGitHubDelivery(db: Db, deliveryId: string, eventName: string, body: string) { const account = JSON.parse(body)?.installation?.account?.login; if (!approvedInstallationAccount(account)) return false; try { await db.inboxDeliveries.insertOne({ _id: `github:${deliveryId}`, provider: "github", deliveryId, payload: body, eventName, status: "pending", attempts: 0, receivedAt: new Date() }); return true; } catch (error) { if ((error as { code?: number }).code === 11000) return false; throw error; } }
export async function notifyUser(db: Db, userId: string, transitionKey: string, title: string, body: string, link?: string) { try { await db.notifications.insertOne({ _id: randomUUID(), userId, transitionKey, title, body, link, createdAt: new Date() }); } catch (error) { if ((error as { code?: number }).code !== 11000) throw error; } }
export async function notifyBoundUsers(db: Db, installationId: string, key: string, title: string, body: string) { const users = await db.users.find({ "installations.installationId": installationId }, { projection: { _id: 1 } }).toArray(); await Promise.all(users.map((user) => notifyUser(db, user._id, key, title, body))); }
const id = (value: unknown) => typeof value === "number" || typeof value === "string" ? String(value) : null;
const safeUrl = (value: unknown) => URL.canParse(String(value)) && ["http:", "https:"].includes(new URL(String(value)).protocol) ? new URL(String(value)).toString() : undefined;
const branch = (value: unknown) => typeof value === "string" && value.length <= 255 && /^[A-Za-z0-9._/-]+$/.test(value) && !value.includes("..") ? value : undefined;
async function projectGitHub(db: Db, event: string, raw: string, fetchTasks?: (input: { installationId: string; repositoryId: string; path: string; sha: string }) => Promise<string | null>, reviewBot?: ReviewBotConfig) {
  const data = JSON.parse(raw) as any, installationId = id(data.installation?.id), repositoryId = id(data.repository?.id); let terminalTransition = false; const mergeabilityUsers = new Set<string>();
  if (!installationId || !repositoryId || !approvedInstallationAccount(data.installation?.account?.login)) return "ignored";
  const users = await db.users.find({ "installations.installationId": installationId }, { projection: { _id: 1 } }).toArray();
  for (const user of users) await mutateUser(db, user._id, (aggregate) => {
    const installation = aggregate.installations.find((item) => item.installationId === installationId); if (!installation) return;
    let repository = installation.repositories.find((item) => item.repositoryId === repositoryId); if (!repository) { repository = { repositoryId, full_name: data.repository?.full_name ?? repositoryId, pullRequests: [], openSpecs: [], deployments: [] }; installation.repositories.push(repository); }
    const pr = data.pull_request;
    if (event === "pull_request" && pr) { const index = repository.pullRequests.findIndex((item) => item.number === Number(pr.number)); if (data.action === "closed" || pr.state !== "open" || pr.user?.login !== aggregate.github.login) { if (index >= 0) repository.pullRequests.splice(index, 1); } else { const previous = index >= 0 ? repository.pullRequests[index] : undefined; if (previous && pr.mergeable != null && previous.mergeable !== String(pr.mergeable)) mergeabilityUsers.add(aggregate._id); const headRef = branch(pr.head?.ref), next: any = { ...previous, number: Number(pr.number), title: pr.title ?? "Untitled", url: pr.html_url, author_login: pr.user?.login, state: pr.state, draft: pr.draft ? 1 : 0, head_ref: headRef, head_sha: typeof pr.head?.sha === "string" && /^[0-9a-f]{40}$/i.test(pr.head.sha) ? pr.head.sha : undefined, mergeable: String(pr.mergeable ?? "unknown"), updated_at: pr.updated_at ?? new Date().toISOString() }; if (!headRef) delete next.head_ref; if (index >= 0) repository.pullRequests[index] = next; else repository.pullRequests.push(next); }
    } else if (["pull_request_review", "check_run", "check_suite", "workflow_run"].includes(event)) { const number = Number(data.pull_request?.number ?? data.check_run?.pull_requests?.[0]?.number ?? data.check_suite?.pull_requests?.[0]?.number ?? data.workflow_run?.pull_requests?.[0]?.number); const target = repository.pullRequests.find((item) => item.number === number); if (target) { if (event === "pull_request_review") target.review_state = data.review?.state ?? data.action; if (event === "check_run" || event === "check_suite") target.checks_state = data.check_run?.conclusion ?? data.check_suite?.conclusion ?? "pending"; if (event === "workflow_run") target.workflow_state = data.workflow_run?.conclusion ?? data.workflow_run?.status ?? "pending"; }
    } else if (event === "issue_comment" && ["created", "edited"].includes(String(data.action)) && reviewBot && data.issue?.pull_request) { const target = repository.pullRequests.find((item) => item.number === Number(data.issue.number)); const actor = data.comment?.user?.login, text = String(data.comment?.body ?? "").toLowerCase(); if (target && typeof actor === "string" && actor.toLowerCase() === reviewBot.login.toLowerCase()) { const state = text.includes(reviewBot.doneMarker.toLowerCase()) ? "complete" : text.includes(reviewBot.startMarker.toLowerCase()) ? "in_progress" : undefined; if (state) { target.bot_review_actor = actor; target.bot_review_state = state; } }
    } else if ((event === "deployment" || event === "deployment_status") && data.deployment) { const deploymentId = id(data.deployment.id); if (deploymentId) { const index = repository.deployments.findIndex((item) => item.id === deploymentId); const prior = index >= 0 ? repository.deployments[index] : {}; const updatedAt = data.deployment_status?.created_at ?? data.deployment.created_at ?? new Date().toISOString(), nextState = event === "deployment_status" ? String(data.deployment_status?.state ?? "pending").toLowerCase() : String(prior.state ?? "pending"), terminal = ["success", "failure", "error"].includes(String(prior.state)); if ((!prior.updated_at || Date.parse(String(updatedAt)) >= Date.parse(String(prior.updated_at))) && !(terminal && nextState === "pending")) { terminalTransition ||= ["success", "failure", "error"].includes(nextState) && prior.state !== nextState; const next = { ...prior, id: deploymentId, environment: data.deployment.environment ?? prior.environment, ref: data.deployment.ref ?? prior.ref, sha: data.deployment.sha ?? prior.sha, state: nextState, target_url: safeUrl(data.deployment_status?.target_url) ?? prior.target_url, log_url: safeUrl(data.deployment_status?.log_url) ?? prior.log_url, updated_at: updatedAt }; if (index >= 0) repository.deployments[index] = next; else repository.deployments.push(next); repository.deployments.sort((a, b) => String(b.updated_at).localeCompare(String(a.updated_at))); repository.deployments = repository.deployments.slice(0, 20); } }
    }
  });
  if (event === "push" && fetchTasks) { const files = (data.commits ?? []).flatMap((commit: any) => [...(commit.added ?? []), ...(commit.modified ?? []), ...(commit.removed ?? [])]); const sourceRef = data.ref?.startsWith("refs/heads/") ? branch(data.ref.slice(11)) : undefined; for (const path of changedTaskPaths(files)) { const deleted = (data.commits ?? []).some((commit: any) => (commit.removed ?? []).includes(path)); const content = deleted ? undefined : await fetchTasks({ installationId, repositoryId, path, sha: data.after ?? "unknown" }); if (!deleted && content === null) throw new Error("OpenSpec artifact fetch failed"); const completed = await projectOpenSpec(db, { installationId, repositoryId, path, content: content ?? "", deleted, sha: data.after ?? "unknown", sourceRef }); if (completed) await notifyBoundUsers(db, installationId, `openspec-complete:${repositoryId}:${path}:${data.after}`, "OpenSpec complete", path.split("/")[2] ?? "OpenSpec"); } }
  if (event === "deployment_status" && terminalTransition) await notifyBoundUsers(db, installationId, `github-deployment:${repositoryId}:${data.deployment?.id}:${String(data.deployment_status.state).toLowerCase()}`, `Deployment ${String(data.deployment_status.state).toLowerCase()}`, data.repository?.full_name ?? "Repository");
  for (const userId of mergeabilityUsers) await notifyUser(db, userId, `mergeability:${repositoryId}:${data.pull_request.number}:${data.pull_request.mergeable}`, "Mergeability changed", data.pull_request.title ?? "Pull request");
  if (event === "pull_request" && data.action === "review_requested" && data.requested_reviewer?.id) { const target = await db.users.findOne({ _id: String(data.requested_reviewer.id) }); if (target) await notifyUser(db, target._id, `review-request:${repositoryId}:${data.pull_request?.number}:${target._id}`, "Review requested", data.pull_request?.title ?? "Pull request"); }
  if ((event === "check_run" || event === "check_suite") && ["failure", "timed_out", "cancelled"].includes(String(data.check_run?.conclusion ?? data.check_suite?.conclusion))) { const number = Number(data.check_run?.pull_requests?.[0]?.number ?? data.check_suite?.pull_requests?.[0]?.number); for (const candidate of await db.users.find({ "installations.installationId": installationId }).toArray()) if (candidate.installations.find((item) => item.installationId === installationId)?.repositories.find((repository) => repository.repositoryId === repositoryId)?.pullRequests.some((pr) => pr.number === number)) await notifyUser(db, candidate._id, `check-failed:${repositoryId}:${number}`, "Checks failed", data.repository?.full_name ?? "Repository"); }
  return "done";
}
export async function drainInbox(db: Db, fetchTasks?: (input: { installationId: string; repositoryId: string; path: string; sha: string }) => Promise<string | null>, reviewBot?: ReviewBotConfig, sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms)), now = () => new Date()) {
  const affected = new Set<string>();
  while (true) {
    const current = now(), rows = await db.inboxDeliveries.find({ status: { $in: ["pending", "pending_verification"] }, $or: [{ nextAttemptAt: { $exists: false } }, { nextAttemptAt: { $lte: current } }] }).sort({ receivedAt: 1 }).toArray();
    for (const row of rows) try { if (row.provider !== "github") { await db.inboxDeliveries.updateOne({ _id: row._id }, { $set: { status: "rejected", processedAt: now() }, $unset: { payload: "", nextAttemptAt: "" } }); continue; } const status = await projectGitHub(db, row.eventName, row.payload ?? "", fetchTasks, reviewBot); const installationId = id(JSON.parse(row.payload ?? "{}").installation?.id); if (installationId) (await db.users.find({ "installations.installationId": installationId }, { projection: { _id: 1 } }).toArray()).forEach((user) => affected.add(user._id)); await db.inboxDeliveries.updateOne({ _id: row._id }, { $set: { status: status === "ignored" ? "ignored" : "done", processedAt: now() }, $unset: { payload: "", error: "", nextAttemptAt: "" } }); } catch (error) { const attempts = row.attempts + 1, terminal = attempts >= 3; await db.inboxDeliveries.updateOne({ _id: row._id }, { $set: { status: terminal ? "rejected" : "pending", attempts, error: error instanceof Error ? error.message.slice(0, 200) : "processing failed", ...(terminal ? { processedAt: now() } : { nextAttemptAt: new Date(now().getTime() + 1000 * 2 ** (attempts - 1)) }) }, ...(terminal ? { $unset: { nextAttemptAt: "" } } : {}) }); }
    const next = await db.inboxDeliveries.find({ status: { $in: ["pending", "pending_verification"] }, nextAttemptAt: { $exists: true } }).sort({ nextAttemptAt: 1 }).limit(1).next();
    if (!next?.nextAttemptAt) break;
    await sleep(Math.max(0, next.nextAttemptAt.getTime() - now().getTime()));
  }
  return [...affected];
}
