import { createSign } from "node:crypto";
import type { Db } from "./db";
import { mutateUser } from "./db";
import { approvedInstallationAccount } from "./installations";

type FetchLike = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
export type ReadResult = { kind: "changed"; body: unknown } | { kind: "unchanged" } | { kind: "error"; message: string; stale: true };
const base64url = (value: string | Buffer) => Buffer.from(value).toString("base64url");
export function githubAppJwt(appId: string, privateKey: string, now = Math.floor(Date.now() / 1000)) { const header = base64url(JSON.stringify({ alg: "RS256", typ: "JWT" })), payload = base64url(JSON.stringify({ iat: now - 60, exp: now + 540, iss: appId })), signer = createSign("RSA-SHA256"); signer.update(`${header}.${payload}`); signer.end(); return `${header}.${payload}.${signer.sign(privateKey).toString("base64url")}`; }
export async function installationToken(appJwt: string, installationId: string, fetcher: FetchLike = fetch) { const response = await fetcher(`https://api.github.com/app/installations/${installationId}/access_tokens`, { method: "POST", headers: { authorization: `Bearer ${appJwt}`, accept: "application/vnd.github+json" } }); if (!response.ok) throw new Error(`GitHub installation token request failed (${response.status})`); return (await response.json() as { token: string }).token; }
export const retryDelay = (response: Response, attempt: number, now = Date.now()) => {
  const retryable = [429, 502, 503, 504].includes(response.status) || response.status === 403 && response.headers.get("x-ratelimit-remaining") === "0";
  if (!retryable) return undefined;
  const retryAfter = Number(response.headers.get("retry-after")); if (retryAfter > 0) return Math.min(retryAfter * 1000, 60_000);
  const reset = Number(response.headers.get("x-ratelimit-reset")); if (reset * 1000 > now) return Math.min(reset * 1000 - now, 60_000);
  return Math.min(1000 * 2 ** attempt, 60_000);
};
const safeUrl = (value: unknown) => URL.canParse(String(value)) && ["http:", "https:"].includes(new URL(String(value)).protocol) ? new URL(String(value)).toString() : undefined;
const nextLink = (header: string | null) => header?.split(",").map((value) => value.trim().match(/^<([^>]+)>;\s*rel="next"$/)).find(Boolean)?.[1];
async function pagedGet(db: Db, key: string, url: string, fetcher: FetchLike): Promise<ReadResult> { const all: unknown[] = []; let next: string | undefined = url, pageNumber = 0; while (next) { const pageKey = `${key}:page:${pageNumber++}`, cached = await db.providerCache.findOne({ _id: pageKey }); let response: Response | undefined; for (let attempt = 0; attempt < 3; attempt++) { response = await fetcher(next, { headers: cached?.etag ? { accept: "application/vnd.github+json", "if-none-match": cached.etag } : { accept: "application/vnd.github+json" } }); const delay = retryDelay(response, attempt); if (delay === undefined || attempt === 2) break; await new Promise((resolve) => setTimeout(resolve, delay)); } if (!response || !response.ok && response.status !== 304) return { kind: "error", message: `GitHub request failed (${response?.status ?? "unknown"})`, stale: true }; const page = response.status === 304 ? cached?.body : await response.json(); if (page === undefined) return { kind: "error", message: "GitHub cached page is unavailable", stale: true }; if (!Array.isArray(page) && !Array.isArray((page as any).repositories)) return { kind: "error", message: "GitHub pagination payload was invalid", stale: true }; const following = response.status === 304 ? cached?.nextUrl : nextLink(response.headers.get("link")); if (response.status !== 304) await db.providerCache.updateOne({ _id: pageKey }, { $set: { etag: response.headers.get("etag") ?? undefined, body: page, nextUrl: following, updatedAt: new Date() } }, { upsert: true }); all.push(...(Array.isArray(page) ? page : (page as any).repositories)); next = following; } await db.providerCache.updateOne({ _id: key }, { $set: { body: all, updatedAt: new Date() } }, { upsert: true }); return { kind: "changed", body: all }; }
export async function conditionalGet(db: Db, key: string, url: string, fetcher: FetchLike = fetch): Promise<ReadResult> { const cached = await db.providerCache.findOne({ _id: key }); let response: Response | undefined; for (let attempt = 0; attempt < 3; attempt++) { response = await fetcher(url, { headers: cached?.etag ? { "if-none-match": cached.etag, accept: "application/vnd.github+json" } : { accept: "application/vnd.github+json" } }); const delay = retryDelay(response, attempt); if (delay === undefined || attempt === 2) break; await new Promise((resolve) => setTimeout(resolve, delay)); } if (!response) return { kind: "error", message: "GitHub request failed", stale: true }; if (response.status === 304) { await db.providerCache.updateOne({ _id: key }, { $set: { updatedAt: new Date() } }); return cached?.body === undefined ? { kind: "error", message: "GitHub cached response is unavailable", stale: true } : { kind: "changed", body: cached.body }; } if (!response.ok) return { kind: "error", message: `GitHub request failed (${response.status})`, stale: true }; const body = await response.json(); await db.providerCache.updateOne({ _id: key }, { $set: { etag: response.headers.get("etag") ?? undefined, body, updatedAt: new Date() } }, { upsert: true }); return { kind: "changed", body }; }
export async function reconcileSerial(db: Db, keys: string[], fetcher: FetchLike, sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))) { const results: ReadResult[] = []; for (const key of keys) { let result: ReadResult = { kind: "error", message: "not requested", stale: true }; for (let attempt = 0; attempt < 3; attempt++) { result = await conditionalGet(db, key, key, fetcher); if (result.kind !== "error" || attempt === 2) break; await sleep(1000 * 2 ** attempt); } results.push(result); } return results; }
export async function bootstrapInstallation(db: Db, installationId: string, token: string, fetcher: FetchLike = fetch): Promise<ReadResult> {
  const request: FetchLike = (url, init) => fetcher(url, { ...init, headers: { ...Object.fromEntries(new Headers(init?.headers)), authorization: `Bearer ${token}` } });
  const bound = await db.users.findOne({ "installations.installationId": installationId }, { projection: { installations: 1 } });
  const known = bound?.installations.find((item) => item.installationId === installationId); if (!known || !approvedInstallationAccount(known.accountLogin)) return { kind: "error", stale: true, message: "installation account is not approved" };
  const installation = await conditionalGet(db, `installation:${installationId}:identity`, "https://api.github.com/installation", request); if (installation.kind === "error") return installation; if (installation.kind !== "changed" || !approvedInstallationAccount((installation.body as any)?.account?.login)) return { kind: "error", stale: true, message: "installation account is not approved" };
  const repos = await pagedGet(db, `installation:${installationId}:repos`, "https://api.github.com/installation/repositories?per_page=100", request); if (repos.kind !== "changed") return repos;
  const repositories = repos.body as Array<{ id: number; full_name: string }>;
  const snapshots = [] as Array<{ repositoryId: string; full_name: string; pullRequests: any[]; openSpecs: Record<string, unknown>[]; deployments: Record<string, unknown>[] }>;
  for (const repo of repositories) { const prs = await pagedGet(db, `installation:${installationId}:repo:${repo.id}:prs`, `https://api.github.com/repositories/${repo.id}/pulls?state=open&per_page=100`, request); if (prs.kind !== "changed") return prs; const deployments = await bootstrapDeployments(db, installationId, String(repo.id), token, fetcher); if (deployments.kind === "error") return deployments; const deploymentRows = deployments.kind === "changed" ? deployments.body : []; snapshots.push({ repositoryId: String(repo.id), full_name: repo.full_name, pullRequests: Array.isArray(prs.body) ? prs.body.map((pr: any) => ({ number: pr.number, title: pr.title, url: pr.html_url, author_login: pr.user?.login, state: pr.state, draft: pr.draft ? 1 : 0, head_ref: pr.head?.ref, head_sha: pr.head?.sha, updated_at: pr.updated_at })) : [], openSpecs: [], deployments: deploymentRows as Record<string, unknown>[] }); }
  const users = await db.users.find({ "installations.installationId": installationId }, { projection: { _id: 1 } }).toArray();
  await Promise.all(users.map((user) => mutateUser(db, user._id, (aggregate) => { const installation = aggregate.installations.find((item) => item.installationId === installationId); if (installation) { installation.repositories = snapshots.map((snapshot) => { const previous = installation.repositories.find((repository) => repository.repositoryId === snapshot.repositoryId); return { ...snapshot, pullRequests: snapshot.pullRequests.filter((pr) => pr.author_login === aggregate.github.login).map((pr) => { const old = previous?.pullRequests.find((item) => item.number === pr.number); return { ...old, ...pr }; }), openSpecs: previous?.openSpecs ?? [], deployments: snapshot.deployments.slice(0, 20) }; }); installation.lastSuccessfulSyncAt = new Date(); delete installation.lastSyncError; } })));
  return repos;
}
export async function bootstrapDeployments(db: Db, installationId: string, repositoryId: string, token: string, fetcher: FetchLike = fetch): Promise<ReadResult> {
  const request: FetchLike = (url, init) => fetcher(url, { ...init, headers: { ...Object.fromEntries(new Headers(init?.headers)), authorization: `Bearer ${token}` } });
  const list = await pagedGet(db, `installation:${installationId}:repo:${repositoryId}:deployments`, `https://api.github.com/repositories/${repositoryId}/deployments?per_page=20`, request);
  if (list.kind !== "changed" || !Array.isArray(list.body)) return list;
  const deployments: Record<string, unknown>[] = [];
  for (const deployment of (list.body as any[]).slice(0, 20)) { const status = await conditionalGet(db, `installation:${installationId}:repo:${repositoryId}:deployment:${deployment.id}:statuses`, `https://api.github.com/repositories/${repositoryId}/deployments/${deployment.id}/statuses?per_page=1`, request); if (status.kind === "error") return status; const latest = status.kind === "changed" && Array.isArray(status.body) ? status.body[0] : undefined; deployments.push({ id: String(deployment.id), environment: deployment.environment, ref: deployment.ref, sha: deployment.sha, state: latest?.state ?? "pending", target_url: safeUrl(latest?.target_url), log_url: safeUrl(latest?.log_url), updated_at: latest?.created_at ?? deployment.created_at ?? new Date().toISOString() }); }
  return { kind: "changed", body: deployments };
}
export async function reconcileInstallations(db: Db, tokenFor: (installationId: string) => Promise<string>, fetcher: FetchLike = fetch) {
  const ids = [...new Set((await db.users.find({}, { projection: { installations: 1 } }).toArray()).flatMap((user) => user.installations.filter((item) => approvedInstallationAccount(item.accountLogin)).map((item) => item.installationId)))].sort();
  const results: Array<{ installationId: string; result: ReadResult }> = [];
  for (const installationId of ids) { let result: ReadResult; try { result = await bootstrapInstallation(db, installationId, await tokenFor(installationId), fetcher); } catch { result = { kind: "error", stale: true, message: "reconciliation failed" }; } results.push({ installationId, result }); if (result.kind === "error") { const users = await db.users.find({ "installations.installationId": installationId }, { projection: { _id: 1 } }).toArray(); await Promise.all(users.map((user) => mutateUser(db, user._id, (aggregate) => { const installation = aggregate.installations.find((item) => item.installationId === installationId); if (installation) installation.lastSyncError = result.message.slice(0, 200); }))); } }
  const failures = results.filter((item) => item.result.kind === "error"); if (failures.length) throw new Error(`reconciliation failed for installations ${failures.map((item) => item.installationId).join(",")}`); return results;
}
