import { randomUUID } from "node:crypto";
import type { Config } from "./config";
import { loadConfig } from "./config";
import type { Db } from "./db";
import { openDatabase } from "./db";
import { bindInstallation, consumeOAuthState, createOAuthState, createSession, dashboardForUser, sessionUser } from "./access";
import { acceptGitHubDelivery, acceptRailwayHint, drainInbox, githubSignatureValid } from "./events";
import { githubAppJwt, installationToken, bootstrapInstallation, reconcileInstallations } from "./github";
import { verifyRailwayDeployment } from "./railway";
import { bindRailwayConnection } from "./access";

const cookie = (request: Request) => request.headers.get("cookie")?.match(/(?:^|; )dcc_session=([^;]+)/)?.[1];
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#18212f"><link rel="manifest" href="/manifest.webmanifest"><link rel="stylesheet" href="/app.css"><title>Command center</title></head><body><main id="app" aria-live="polite"><p>Loading command center…</p></main><script type="module" src="/app.js"></script></body></html>`;
const css = `:root{font:14px system-ui;color:#172033;background:#f5f7f9}body{margin:0}main{max-width:1200px;margin:auto;padding:24px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:12px}.card{border:1px solid #d9e0e7;border-radius:8px;background:#fff;padding:16px}.status{font-size:12px;padding:2px 7px;border-radius:99px;background:#e8eef5}.green{background:#dcfae6;color:#067647}.red{background:#fee4e2;color:#b42318}.yellow{background:#fef0c7;color:#b54708}.blue{background:#dbeafe;color:#1d4ed8}.error{color:#b42318}button:focus-visible,a:focus-visible{outline:3px solid #2563eb;outline-offset:2px}@media(max-width:500px){main{padding:12px}}`;
const js = `const root=document.querySelector('#app'),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),tone=s=>/success|open|complete/i.test(s)?'green':/fail|error|closed/i.test(s)?'red':/pending|stale/i.test(s)?'yellow':'blue';let known=null;const render=x=>{if(x.error)return root.innerHTML='<div class="card error">'+esc(x.error)+' <a href="/auth/github">Sign in</a></div>';if(!x.installationCount)return root.innerHTML='<div class="card"><h1>Command center</h1><p>No repositories connected.</p><a href="/install/github">Install GitHub App</a></div>';const rows=(items,empty,fn)=>items.length?items.map(fn).join(''):('<p>'+empty+'</p>');root.innerHTML='<header><h1>Command center</h1><button id="notify">Enable notifications</button></header><div class="grid"><section class="card"><h2>Open pull requests</h2>'+rows(x.pullRequests,'Nothing open.',p=>'<p>#'+esc(p.number)+' '+esc(p.title)+' <span class="status '+tone(p.state)+'">'+esc(p.state)+'</span></p>')+'</section><section class="card"><h2>OpenSpec</h2>'+rows(x.openSpecs,'No committed OpenSpecs.',o=>'<p>'+esc(o.change_name)+' '+esc(o.completed)+'/'+esc(o.total)+'</p>')+'</section><section class="card"><h2>Deployments</h2>'+rows(x.deployments,'No verified deployments.',d=>'<p><span class="status '+tone(d.status)+'">'+esc(d.status)+'</span></p>')+'</section></div>';document.querySelector('#notify')?.addEventListener('click',()=>globalThis.Notification?.requestPermission())};const load=()=>fetch('/api/snapshot').then(r=>r.ok?r.json():Promise.reject(r.status)).then(x=>{const ids=new Set(x.notifications.map(n=>n.id));if(known&&globalThis.Notification?.permission==='granted')navigator.serviceWorker?.ready.then(sw=>x.notifications.filter(n=>!known.has(n.id)).forEach(n=>sw.showNotification(n.title,{body:n.body})));known=ids;render(x);return true}).catch(()=>{render({error:navigator.onLine?'Sign in to view your command center.':'Offline: live command-center data is unavailable.'});return false});load().then(ok=>{if(ok)new EventSource('/events').addEventListener('refresh',load)});navigator.serviceWorker?.register('/sw.js');`;
const manifest = JSON.stringify({ name: "Developer Command Center", short_name: "Command Center", start_url: "/", display: "standalone", background_color: "#f5f7f9", theme_color: "#18212f", icons: [{ src: "/icon-192.svg", sizes: "192x192", type: "image/svg+xml", purpose: "any" }, { src: "/icon-512.svg", sizes: "512x512", type: "image/svg+xml", purpose: "any maskable" }] });
const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#18212f"/><path d="M17 20h30v6H17zm0 12h30v6H17zm0 12h20v6H17z" fill="#7dd3fc"/></svg>`;
const worker = `const CACHE='dcc-shell-v1';const ASSETS=['/','/app.css','/app.js','/manifest.webmanifest','/icon-192.svg','/icon-512.svg'];self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS))));self.addEventListener('fetch',e=>{const u=new URL(e.request.url);if(e.request.method==='GET'&&ASSETS.includes(u.pathname))e.respondWith(caches.match(e.request).then(x=>x||fetch(e.request)));});`;

export function createApp(db: Db, config: Config) {
  const streams = new Map<string, Set<ReadableStreamDefaultController<Uint8Array>>>();
  const encoder = new TextEncoder();
  const refresh = (userId: string) => { for (const controller of streams.get(userId) ?? []) controller.enqueue(encoder.encode("event: refresh\ndata: {}\n\n")); };
  let draining = Promise.resolve();
  const boundedBody = async (request: Request, limit = 1_000_000) => { if (Number(request.headers.get("content-length") ?? 0) > limit) return null; const reader = request.body?.getReader(); if (!reader) return ""; let size = 0, text = ""; while (true) { const { done, value } = await reader.read(); if (done) return text; size += value.byteLength; if (size > limit) return null; text += new TextDecoder().decode(value, { stream: true }); } };
  const githubTasks = async (input: { installationId: string; repositoryId: string; path: string; sha: string }) => { if (!config.githubAppId || !config.githubAppPrivateKey) return null; const token = await installationToken(githubAppJwt(config.githubAppId, config.githubAppPrivateKey.replace(/\\n/g, "\n")), input.installationId); const response = await fetch(`https://api.github.com/repositories/${input.repositoryId}/contents/${input.path}?ref=${input.sha}`, { headers: { authorization: `Bearer ${token}`, accept: "application/vnd.github.raw" } }); return response.ok ? response.text() : null; };
  const scheduleDrain = () => { draining = draining.catch((error) => console.error("webhook drain failed", error instanceof Error ? error.message.slice(0, 200) : "unknown error")).then(() => drainInbox(db, config.railwayApiToken ? (hint) => verifyRailwayDeployment(config.railwayApiToken!, hint) : undefined, githubTasks).then((users) => users.forEach(refresh))); return draining; };
  const authenticated = (request: Request) => { const token = cookie(request); return token ? sessionUser(db, token) : null; };
  return { async fetch(request: Request) {
    const url = new URL(request.url), path = url.pathname;
    const asset = (value: string, type: string, headers: HeadersInit = {}) => new Response(value, { headers: { "content-type": type, ...headers } });
    if (path === "/") return asset(html, "text/html; charset=utf-8");
    if (path === "/app.css") return asset(css, "text/css"); if (path === "/app.js") return asset(js, "text/javascript"); if (path === "/manifest.webmanifest") return asset(manifest, "application/manifest+json"); if (["/icon.svg", "/icon-192.svg", "/icon-512.svg"].includes(path)) return asset(icon, "image/svg+xml"); if (path === "/sw.js") return asset(worker, "text/javascript", { "cache-control": "no-cache" });
    if (path === "/api/snapshot") { const user = authenticated(request); return user ? Response.json(dashboardForUser(db, user.id)) : new Response("unauthenticated", { status: 401 }); }
    if (path === "/events") { const user = authenticated(request); if (!user) return new Response("unauthenticated", { status: 401 }); const stream = new ReadableStream<Uint8Array>({ start(controller) { const set = streams.get(user.id) ?? new Set(); set.add(controller); streams.set(user.id, set); controller.enqueue(encoder.encode("event: refresh\ndata: {}\n\n")); request.signal.addEventListener("abort", () => { set.delete(controller); if (!set.size) streams.delete(user.id); }); } }); return new Response(stream, { headers: { "content-type": "text/event-stream", "cache-control": "no-cache", connection: "keep-alive" } }); }
    if (path === "/auth/github") { if (!config.githubClientId) return new Response("GitHub OAuth is not configured", { status: 503 }); const state = createOAuthState(db); return Response.redirect(`https://github.com/login/oauth/authorize?client_id=${encodeURIComponent(config.githubClientId)}&state=${encodeURIComponent(state)}`, 302); }
    if (path === "/install/github") { const user = authenticated(request); if (!user || !config.githubAppSlug) return new Response("GitHub App installation is not configured", { status: 503 }); const state = createOAuthState(db); return Response.redirect(`https://github.com/apps/${encodeURIComponent(config.githubAppSlug)}/installations/new?state=${encodeURIComponent(state)}`, 302); }
    if (path === "/auth/github/callback") { const code = url.searchParams.get("code"), state = url.searchParams.get("state"), installation = url.searchParams.get("installation_id"); if (!code || !state || !consumeOAuthState(db, state) || !config.githubClientId || !config.githubClientSecret) return new Response("invalid OAuth callback", { status: 400 }); const tokenResponse = await fetch("https://github.com/login/oauth/access_token", { method: "POST", headers: { accept: "application/json", "content-type": "application/json" }, body: JSON.stringify({ client_id: config.githubClientId, client_secret: config.githubClientSecret, code }) }); const accessToken = (await tokenResponse.json() as { access_token?: string }).access_token; if (!accessToken) return new Response("GitHub sign-in failed", { status: 502 }); const identity = await (await fetch("https://api.github.com/user", { headers: { authorization: `Bearer ${accessToken}`, accept: "application/vnd.github+json" } })).json() as { id: number; login: string; avatar_url?: string }; const id = String(identity.id); db.query("INSERT INTO users (id,github_id,login,avatar_url) VALUES (?,?,?,?) ON CONFLICT(github_id) DO UPDATE SET login=excluded.login,avatar_url=excluded.avatar_url").run(id, id, identity.login, identity.avatar_url ?? null); if (installation && /^\d+$/.test(installation)) { const list = await (await fetch("https://api.github.com/user/installations", { headers: { authorization: `Bearer ${accessToken}`, accept: "application/vnd.github+json" } })).json() as { installations?: Array<{ id: number }> }; if (list.installations?.some((item) => String(item.id) === installation)) bindInstallation(db, id, installation); else return new Response("unverified installation", { status: 403 }); } const session = createSession(db, id); return new Response(null, { status: 302, headers: { location: new URL("/", url).toString(), "set-cookie": `dcc_session=${session.token}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=2592000` } }); }
    if (path === "/auth/github/setup") return new Response("unverified installation binding is not supported", { status: 410 });
    if (path === "/api/railway/connections") { const user = authenticated(request); if (!user) return new Response("unauthenticated", { status: 401 }); if (request.method !== "POST") return new Response("method not allowed", { status: 405 }); let value: { projectId?: string; serviceId?: string; environmentId?: string }; try { value = await request.json(); } catch { return new Response("invalid JSON", { status: 400 }); } if (![value.projectId, value.serviceId, value.environmentId].every((x) => x && /^[\w-]+$/.test(x))) return new Response("invalid Railway connection", { status: 400 }); bindRailwayConnection(db, user.id, value.projectId!, value.serviceId!, value.environmentId!); return new Response(null, { status: 204 }); }
    if (path === "/health") return Response.json({ ok: true });
    if (path === "/ready") { try { db.query("SELECT 1").get(); return Response.json({ ok: true }); } catch { return new Response("not ready", { status: 503 }); } }
    if (path === "/webhooks/github" && request.method === "POST") { const body = await boundedBody(request), delivery = request.headers.get("x-github-delivery"), event = request.headers.get("x-github-event"); if (body === null) return new Response("payload too large", { status: 413 }); if (!delivery || !event || !config.githubWebhookSecret || !githubSignatureValid(body, request.headers.get("x-hub-signature-256"), config.githubWebhookSecret)) return new Response("invalid GitHub webhook", { status: 401 }); const inserted = acceptGitHubDelivery(db, delivery, event, body); if (inserted) queueMicrotask(() => void scheduleDrain()); return new Response(null, { status: 202 }); }
    if (path.startsWith("/webhooks/railway/") && request.method === "POST") { const token = path.slice("/webhooks/railway/".length); if (!config.railwayWebhookToken || token !== config.railwayWebhookToken) return new Response("not found", { status: 404 }); const body = await boundedBody(request); if (body === null) return new Response("payload too large", { status: 413 }); acceptRailwayHint(db, request.headers.get("x-request-id") ?? randomUUID(), body); queueMicrotask(() => void scheduleDrain()); return new Response(null, { status: 202 }); }
    const repair = path.match(/^\/api\/installations\/(\d+)\/(bootstrap|repair)$/); if (repair && request.method === "POST") { const user = authenticated(request), installationId = repair[1]; if (!user || !(db.query("SELECT 1 FROM user_installations WHERE user_id=? AND installation_id=?").get(user.id, installationId))) return new Response("not found", { status: 404 }); if (!config.githubAppId || !config.githubAppPrivateKey) return new Response("GitHub App is not configured", { status: 503 }); const token = await installationToken(githubAppJwt(config.githubAppId, config.githubAppPrivateKey.replace(/\\n/g, "\n")), installationId); return Response.json(await bootstrapInstallation(db, installationId, token)); }
    return new Response("not found", { status: 404 });
  } };
}
if (import.meta.main) { const config = loadConfig(); const db = openDatabase(config.databasePath); const app = createApp(db, config); Bun.serve({ port: config.port, fetch: app.fetch }); void drainInbox(db, config.railwayApiToken ? (hint) => verifyRailwayDeployment(config.railwayApiToken!, hint) : undefined); if (config.githubAppId && config.githubAppPrivateKey) { const reconcile = () => reconcileInstallations(db, (id) => installationToken(githubAppJwt(config.githubAppId!, config.githubAppPrivateKey!.replace(/\\n/g, "\n")), id)).catch((error) => console.error("reconciliation failed", error instanceof Error ? error.message.slice(0, 200) : "unknown error")); setInterval(reconcile, config.reconcileIntervalMs); } }
